# Generated by Django 5.1.4 on 2025-06-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_emails',
            field=models.BooleanField(default=False),
        ),
    ]
