# Generated by Django 5.1.4 on 2025-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0003_answer_unique_correct_answer_per_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessments',
            name='trial',
            field=models.PositiveIntegerField(),
        ),
    ]
