# Generated by Django 5.1.4 on 2025-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0004_alter_userassessments_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessments',
            name='score_percentage',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_score',
            field=models.FloatField(),
        ),
    ]
