# Generated by Django 5.1.4 on 2025-01-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0007_alter_assessment_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='text',
            field=models.JSONField(default='Default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
