# Generated by Django 5.1.4 on 2025-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0008_module_text_alter_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='text',
            field=models.JSONField(default=list),
        ),
    ]
