# Generated by Django 5.1.4 on 2025-01-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0009_alter_module_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='dal.module'),
        ),
    ]
