# Generated by Django 5.1.1 on 2025-06-04 19:11

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0010_alter_assessment_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='module',
        ),
        migrations.CreateModel(
            name='PhishingScenario',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('seed', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='dal.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhishingScenario',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IDLE', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='IDLE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phishing_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dal.phishingscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSimulation',
        ),
    ]
