# Generated by Django 5.1.1 on 2025-06-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0011_remove_simulation_module_phishingscenario_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_correct_answer_per_question',
        ),
    ]
