# Generated by Django 5.1.1 on 2025-06-07 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0012_remove_answer_unique_correct_answer_per_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userassessments',
            name='unique_user_assessment_trial',
        ),
        migrations.AlterUniqueTogether(
            name='userassessments',
            unique_together={('user', 'assessment', 'trial')},
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('MODULE', 'Module')], default='INITIAL', max_length=255),
        ),
        migrations.RemoveField(
            model_name='userassessments',
            name='is_passed',
        ),
        migrations.RemoveField(
            model_name='userassessments',
            name='score_percentage',
        ),
    ]
