# Generated by Django 5.1.1 on 2025-06-08 22:21

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0013_remove_userassessments_unique_user_assessment_trial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='max_score',
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, choices=[('AUTHENTICATION_AND_DEVICE_SECURITY', 'Authentication & Device Security'), ('DATA_PRIVACY_AND_RESPONSIBLE_SHARING', 'Data Privacy & Responsible Sharing'), ('FINANCIAL_AND_PAYMENT_SECURITY', 'Financial & Payment Security'), ('PASSWORD_HYGIENE', 'Password Hygiene'), ('PHISHING_AND_SOCIAL_ENGINEERING', 'Phishing & Social Engineering'), ('SAFE_BROWSING_AND_PUBLIC_WIFI', 'Safe Browsing & Public Wi-Fi')], max_length=255, null=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_questions', to='dal.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EssayAnswerRubric',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('weight', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='dal.essayquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, choices=[('AUTHENTICATION_AND_DEVICE_SECURITY', 'Authentication & Device Security'), ('DATA_PRIVACY_AND_RESPONSIBLE_SHARING', 'Data Privacy & Responsible Sharing'), ('FINANCIAL_AND_PAYMENT_SECURITY', 'Financial & Payment Security'), ('PASSWORD_HYGIENE', 'Password Hygiene'), ('PHISHING_AND_SOCIAL_ENGINEERING', 'Phishing & Social Engineering'), ('SAFE_BROWSING_AND_PUBLIC_WIFI', 'Safe Browsing & Public Wi-Fi')], max_length=255, null=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='dal.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dal.mcqquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
