# Generated by Django 5.1.1 on 2025-06-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0014_remove_question_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswerrubric',
            name='is_correct',
        ),
    ]
