# Generated by Django 5.1.4 on 2025-06-17 18:12

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0015_remove_essayanswerrubric_is_correct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={},
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dal.leaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('leaderboard', 'user')},
            },
        ),
    ]
