# Generated by Django 5.1.4 on 2025-06-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0016_alter_leaderboard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessments',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
