# Generated by Django 5.1.4 on 2025-06-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0017_userassessments_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswerrubric',
            name='value',
        ),
    ]
