# Generated by Django 5.1.4 on 2025-06-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0018_remove_essayanswerrubric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_questions_at_once',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userassessments',
            name='max_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
