# Generated by Django 5.1.4 on 2025-06-20 11:45

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0019_assessment_max_questions_at_once_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnswerSubmission',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dal.essayquestion')),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_answers', to='dal.userassessments')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user_assessment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='McqAnswerSubmission',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dal.mcqanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dal.mcqquestion')),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answers', to='dal.userassessments')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user_assessment', 'question')},
            },
        ),
    ]
