# Generated by Django 5.1.4 on 2025-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0020_essayanswersubmission_mcqanswersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='name',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='type',
            field=models.CharField(choices=[('GLOBAL', 'Global')], default='GLOBAL', max_length=255),
        ),
    ]
