# Generated by Django 5.1.4 on 2025-06-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0021_remove_leaderboard_name_leaderboard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='type',
            field=models.CharField(choices=[('GLOBAL', 'Global')], default='GLOBAL', max_length=255, unique=True),
        ),
    ]
