# Generated by Django 5.1.4 on 2025-06-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0022_alter_leaderboard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_questions_at_once',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
