# Generated by Django 5.1.4 on 2025-06-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0023_assessment_max_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphishingscenario',
            name='email_body',
            field=models.TextField(default='DEFAULT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userphishingscenario',
            name='subject',
            field=models.TextField(default='DEFAULT'),
            preserve_default=False,
        ),
    ]
