# Generated by Django 5.1.4 on 2025-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0024_userphishingscenario_email_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphishingscenario',
            name='status',
            field=models.CharField(choices=[('IDLE', 'In Progress'), ('PASSED_OR_IGNORED', 'Passed or Ignored'), ('FAILED', 'Failed')], default='IDLE', max_length=255),
        ),
    ]
