# Generated by Django 5.1.4 on 2025-06-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0025_alter_userphishingscenario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingscenario',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=255),
            preserve_default=False,
        ),
    ]
