# Generated by Django 5.1.4 on 2025-06-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0026_phishingscenario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='total_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
