name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Copy files to Azure VM
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.AZURE_VM_HOST }}
          REMOTE_USER: ${{ secrets.AZURE_VM_USERNAME }}
          SOURCE: './'
          TARGET: /home/icat-api/

      - name: Run remote deployment script on Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y pkg-config python3-dev default-libmysqlclient-dev build-essential

            cd /home/icat-api/

            rm -rf env
            python3 -m venv env
            source env/bin/activate

            pip install -r requirements.txt

            echo "export SECRET_KEY='${{ secrets.SECRET_KEY }}'" >> env/bin/activate
            echo "export DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> env/bin/activate

            python3 manage.py migrate

            bash configs/conf.d/deploy-celery.sh
