# name: Testing CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:latest
#         env:
#           MYSQL_ROOT_PASSWORD: root
#           MYSQL_DATABASE: icat
#         options: >-
#           --health-cmd="mysqladmin ping --silent"
#           --health-interval=10s
#           --health-timeout=5s
#           --health-retries=3
#         ports:
#           - 3306:3306

#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: '3.x'
#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Wait for MySQL
#         run: |
#           echo "Waiting for MySQL to be ready..."
#           for i in {1..60}; do
#             if mysqladmin ping -h"127.0.0.1" --silent; then
#               echo "MySQL is ready!"
#               break
#             fi
#             echo "Waiting for MySQL... ($i)"
#             sleep 2
#           done
#           mysqladmin ping -h"127.0.0.1" --silent
#       - name: Run Tests
#         env:
#           DATABASE_URL: mysql://root:root@127.0.0.1:3306/icat
#           ACCESS_TOKEN_LIFETIME: 3600
#           REFRESH_TOKEN_LIFETIME: 86400
#         run: |
#           python manage.py test
